app = "tchajed-podcast"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

[env]
  DATABASE_URL = "sqlite:///data/podcast.db"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[mounts]
  source = "podcast_data"
  destination = "/data"

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
